vuex + typescript refactoring
DSRCorporation/vue-3-boilerplate pull request #8
Opened 2022-02-04 13:28 UTC by JusJuraev

implemented typings for getters, actions & mutations for both options API & composition API

2022-02-04 15:17 UTC, dmitryrazinkov requested changes

2022-02-04 15:17 UTC, dmitryrazinkov commented on src/scss/breakpoints.scss
> +  xl: 90rem // 1440px,,,
it looks like something strange happened here =) is you your IDE? have run git hooks or `npm run lint` before committing?

2022-02-04 16:59 UTC, JusJuraev commented on src/scss/breakpoints.scss
> +  xl: 90rem // 1440px,,,
I fixed that

2022-02-08 11:15 UTC, dmitryrazinkov approved these changes

2022-02-08 11:15 UTC, merged